server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin@localhost:27017/report_db?authSource=admin}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

service:
  user:
    url: http://user-ms:8080/api/v1

rabbitmq:
  queue:
    name: ${RABBITMQ_QUEUE_NAME:bootcamp.report.queue}